{% set name = "jwt-cpp" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Thalhammer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d45894f57437ce45233cfe0e07383c4e1f32f969edfd8df8347e177b13bf74e5
  patches:
    # don't use find_package for picojson, we know we have it
    - patches/0001-don-t-look-for-external-picojson.patch
    # disable cmake compiler checks on windows
    - patches/0002-disable-cmake-compiler-checks.patch      # [win]

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # package is header-only
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - gmock  # [unix]
    - gtest  # [unix]
    - nlohmann_json
    - openssl
    - picojson
  run:
    - picojson

test:
  commands:
    - test -f ${PREFIX}/include/jwt-cpp/jwt.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/jwt-cpp/jwt-cpp-config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\jwt-cpp\jwt.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\jwt-cpp\jwt-cpp-config.cmake exit 1  # [win]

about:
  home: https://thalhammer.it/projects/jwt_cpp
  dev_url: https://github.com/Thalhammer/jwt-cpp
  summary: A header only library for creating and validating json web tokens in c++
  license: MIT
  license_file: LICENSE
  description: |
    A header only library for creating and validating JSON Web Tokens in C++11.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - eaaltonen
