{% set name = "jwt-cpp" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Thalhammer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6e815d86c168eb521a27937d603747dec0ca3c39ffc12d6fa72e2cf78a5b02d2
  patches:
    - patches/0001-Remove-greater-than-sign-from-link-interface.patch

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # package is header-only
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - openssl
    - picojson >=1.3.0 # build 1 or greater
  run:
    - picojson >=1.3.0 # build 1 or greater

test:
  commands:
    - test -f ${PREFIX}/include/jwt-cpp/jwt.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/jwt-cpp/jwt-cpp-config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\jwt-cpp\jwt.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\jwt-cpp\jwt-cpp-config.cmake exit 1  # [win]

about:
  home: https://thalhammer.it/projects/jwt_cpp
  dev_url: https://github.com/Thalhammer/jwt-cpp
  summary: A header only library for creating and validating json web tokens in c++
  license: MIT
  license_file: LICENSE
  description: |
    A header only library for creating and validating JSON Web Tokens in C++11.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - eaaltonen
