{% set name = "jwt-cpp" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Thalhammer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d8f5ffb361824630b3b6f4aad26c730c915081071040c232ac57947d6177ef4f
  patches:
    # install cmake config files into lib/cmake/
    - cmake-config-install-dir.patch
    # don't use find_package for picojson, we know we have it
    - external-picojson.patch
    # disable cmake compiler checks on windows
    - cmake-no-compiler.patch  # [win]

build:
  ignore_run_exports:
    # we only need the compiler for the test suite
    - libgcc-ng  # [unix]
    - libstdcxx-ng  # [unix]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [unix]
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - gmock  # [unix]
    - gtest  # [unix]
    - openssl
    - picojson

test:
  commands:
    - test -f ${PREFIX}/include/jwt-cpp/jwt.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/jwt-cpp/jwt-cpp-config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\jwt-cpp\jwt.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\jwt-cpp\jwt-cpp-config.cmake exit 1  # [win]

about:
  home: https://thalhammer.it/projects/jwt_cpp
  dev_url: https://github.com/Thalhammer/jwt-cpp
  summary: A header only library for creating and validating json web tokens in c++
  license: MIT
  license_file: LICENSE
  description: |
    A header only library for creating and validating JSON Web Tokens in C++11.

extra:
  recipe-maintainers:
    - duncanmmacleod
